### PR TITLE
Fix codeblock regression and bug

### PR DESCRIPTION
**Pull request by recrwplay**
Fixes issues introduced by cheat sheet selector and updates to codeblocks.

### CODE REVIEW

**Review by ggrossetie — APPROVED** [review]
LGTM 👍🏻

**Comment by jexp** [comment]
Thank you Neil!

The original changes also broke graphgist Cypher rendering across the board. Not sure if any other developer pages were also affected.

**Comment by ggrossetie** [comment]
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

Ooops, time to upgrade 😄

**Comment by recrwplay** [comment]
@jexp The latest commit should restore the graphgist cypher rendering - eg https://deploy-preview-158--docs-ui-spontaneous-bubblegum-e39251.netlify.app/first-steps-with-cypher.html

**Pull request merged**
