### PR TITLE
Add GraphGists UI 

### PR DESCRIPTION
**Pull request by Mogztter**
- Introduce a new "backend" in the runnable code (to execute query against the portal.graphgist GraphQL API)
- Add 3 new layouts
   * GraphGists index page
   * GraphGist page
   * GraphGist category page

### CODE REVIEW

**Comment by Mogztter** [comment]
Thanks @adam-cowley for your review/updated design!
I will add a GraphGist category page in the `ui-model.yml` to make sure that it looks good (using the preview).

**Comment by Mogztter** [comment]
@adam-cowley I think we are good to go?
We can still adjust the design if pages don't look as good with the actual data from the portal.graphgist.org API.

### Index page

localhost_5252_graph-gist-index html(Laptop with HiDPI screen)

### Category page
localhost_5252_graph-gist-category-pop-culture html(Laptop with HiDPI screen)

### GraphGist page
localhost_5252_graph-gist-star-wars-social-network html(Laptop with HiDPI screen)

**Comment by adam-cowley** [comment]
Those cards could probably do with having a white background but apart from that I'm happy to go live with these

**Comment by Mogztter** [comment]
@adam-cowley I found a few issues with the runnable code block component but I'm not entirely sure how to fix them. Maybe we could merge this pull and deploy a first version of the GraphGist site in a staging environment (Netlify?) in order to gather feedback and iron out the last remaining bugs?

**Pull request merged**
