### PR TITLE
resolves #79 configure the connection URL when opening in Neo4j Browser

### LINKED ISSUE #79: Add an input below the "Play as Browser Guide" button to configure the connection URL (to the database)
Here's a mockup:

image

"Database URL" should be renamed "Connection URL".

The default value of "Connection URL" field will be: `bolt://localhost`.

If the query string `dbms` is defined, we will use this value instead of the default value. For instance: https://neo4j.com/graphgists/northwind-recommendation-engine/?dbms=neo4j%2Bs://neo4j@foo.databases.neo4j.io
In this case, the value of the "Connection URL" field will be: `neo4j+s://neo4j@foo.databases.neo4j.io`

The connection URL will be used to update the link on the "Play as Browser Guide" button:

```
https://browser.neo4j.io/?cmd=play&arg=https://guides.neo4j.com/graph-examples/northwind-recommendation-engine/graph_guide&dbms={{connectionUrl}}
```

As you can see, the value of the field "Connection URL" is passed as a query string: `&dbms={{connectionUrl}}` (where `{{connectionUrl}}` is the connection URL filled out by the user).

Please note that we are now using `https://browser.neo4j.io` instead of `neo4j-desktop://graphapps/neo4j-browser`.

//cc @adam-cowley let me know what you think since you've worked on the original design.

### PR DESCRIPTION
**Pull request by Mogztter**
image

Please note that the Neo4j browser URL must be updated in: https://github.com/neo4j-documentation/developer-site-generator/blob/6ed0f86dd124b86d7fbbe4fabe36784e0ad2d6be/lib/graphgists.js#L281

resolves #79

### CODE REVIEW

**Comment by adam-cowley** [comment]
This looks good, exactly what I was thinking for the input box and button.

I _think_ that a fieldset can only be used within a form so might be worth a double-check.  Could you remove the border on it if it is kept?  Everything looks a bit squashed too if you could add some padding?  Otherwise, looks good to go!

**Comment by Mogztter** [comment]
> I think that a fieldset can only be used within a form so might be worth a double-check.

I did check and apparently it can be used in any element that accepts flow content.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Fieldset#technical_summary

> Could you remove the border on it if it is kept? Everything looks a bit squashed too if you could add some padding? Otherwise, looks good to go!

Sure 👍🏻 

Please note that we should upgrade both the UI and the site generator at the same time (because this feature relies on https://github.com/neo4j-documentation/developer-site-generator/commit/51f22aa75a2d3ffa92275bb19643e888776ee149).

**Comment by Mogztter** [comment]
Is it better?

image

**Comment by adam-cowley** [comment]
LGTM 🔥

**Pull request merged**
