### PR TITLE
Changed version selector to Costa's dropdown and relocated to nav-menu

### PR DESCRIPTION
**Pull request by mauvo**

### CODE REVIEW

**Comment by mauvo** [comment]
Fixed in another PR

**Comment by mauvo** [comment]
Oops - thought this was my old broken PR... not the one Adam fixed.

**Comment by recrwplay** [comment]
Once it's merged it will be the style used by all docs everywhere. The only way to keep it from going live is to not publish any updated content to neo4j.com.

**Comment by recrwplay** [comment]
I strongly prefer this location for the version switcher to the existing style.

It doesn't have the tracking that was introduced in #111 to track version-switching events - I don't know if that's being intentionally dropped.

**Comment by davidoliverSP2** [comment]
> I strongly prefer this location for the version switcher to the existing style.
> 
> It doesn't have the tracking that was introduced in #111 to track version-switching events - I don't know if that's being intentionally dropped.

I second this preference 😄

**Comment by adam-cowley** [comment]
@recrwplay  I moved the event tracking code into nav.js

https://github.com/neo4j-documentation/docs-ui/blob/version-dropdown/src/js/01-nav.js#L55-L71

**Comment by recrwplay** [comment]
> @recrwplay I moved the event tracking code into nav.js

Ah, I hadn't spotted that. Excellent!

**Pull request merged**
