### PR TITLE
Remove toc sidebar when page-toclevels is -1

### PR DESCRIPTION
**Pull request by recrwplay**
At narrow page widths, when the main TOC is still visible, setting `:page-toclevel: -1` results in no in-page 'Contents' being displayed, but the HTML elements are still present, taking up width.

This can produce inconsistent page appearance:
- pages with no headings use the available width
- pages with headings, but the 'Contents' section removed use the width minus the width of the `<aside>`.

Note that this change has no effect on the page layout once the `<article>` (the main page content) reaches its maximum width.

### CODE REVIEW

**Comment by stefano-ottolenghi** [comment]
I'm not sure I understand the change. With no ToC, the content is still limited to page width - ToC and doesn't fill up the whole width. 

Screenshot from 2024-08-13 18-04-20
Screenshot from 2024-08-13 18-04-10

**Comment by recrwplay** [comment]
This PR addresses instances from the breakpoint at 1024px where the left and right ToC visibility on the page is toggled. Between this breakpoint and the width at which the page content reaches its maximum width, a ToC that is hidden by using `:page-toclevels: -1` on the page was still taking up space. 

Screenshot 2024-08-14 at 10 29 01

Once the content reaches its current maximum, I don't think we should expand it into the space used by the ToC (essentially: readability and consistency). An exception to this is where the page displays tables (and really, tables only) and where the tables would be more readable if the page uses the full width. I opened #214 (some time ago) with that in mind.

**Comment by stefano-ottolenghi** [comment]
Ah, okay, I had misunderstood its purpose then.

**Review by stefano-ottolenghi — APPROVED** [review]
LGTM.

**Pull request merged**
