### PR TITLE
Added runnable cypher source blocks

### PR DESCRIPTION
**Pull request by adam-cowley**
Adds a footer to Cypher code blocks with a button for running the query against the real database.  The idea is to make the code samples more interactive.

https://user-images.githubusercontent.com/1372869/106926626-2ea71300-6709-11eb-9162-78052dc7109a.mp4

Usage:
1. Include driver using the page attribute - `:page-includedriver: true` _- we could load the code asyncronously if a code block exists on the page instead_
2. Add `role=runnable` to a source block
3. Make it editable by adding `role=editable` - for now this just adds the `contenteditable` attribute to the `<code>` element but in future could be replaced with the new monaco editor
4. Add `role=instant` to the block to get it to run the query and render the results on pageload (top code block)
5. Change the database that the driver session is created with using `role=database:something`
6. Change the access mode with `role=mode:read` or `role=mode:write`

Currently the movie credentials for `demo.neo4jlabs.com` are defaulted - in future it would be nice to let the user choose one of the example use cases (movies, trumpworld, etc) or select their own sandbox/aura instance.

The query is run within a transaction which is then rolledback so no changes are committed to the database.  Either way we should consider how/what database to use and be cautious of people hammering the database.

Attn! @jexp @Mogztter @davidoliverSP2 @recrwplay  @spgandhi  @akollegger 

Suggestions/Roadmap:
- [x] Reset button
- [x] Close results button
- [x] Graph/Table View
- [ ] Editable areas for queries rather than an editing the entire query

### CODE REVIEW

**Comment by spgandhi** [comment]
This is just awesome! I strong usecase I can think of is with GraphAcademy. Right now, a user taking a course in GA, also has to create a sandbox to follow through the content and then constantly switch context between the two. If a user is logged into GraphAcademy, then the Auth0 accessToken can also be used to call Sandbox API endpoints to get the active sandboxes along with credentials.

Combine that with this, we can allow users in GraphAcademy to run query against a Sandbox database from the GraphAcademy UI itself.

**Comment by spgandhi** [comment]
I just read through the previous comments again, and it seems our thoughts are pretty much aligned there @adam-cowley

**Comment by recrwplay** [comment]
Looks great @adam-cowley - we definitely have interest and potential use cases for this in docs.

**Comment by adam-cowley** [comment]
Simple force graph layout

https://user-images.githubusercontent.com/1372869/107217551-3b2bb400-6a06-11eb-872a-c78dba216b63.mov

**Pull request merged**
