### PR TITLE
Add arrows in Labs header

### PR DESCRIPTION
**Pull request by johnymontana**
This PR adds the arrows project into the Labs header

### CODE REVIEW

**Review by Mogztter — APPROVED** [review]
:+1:

**Comment by Mogztter** [comment]
@johnymontana I'm curious, do you know where I can find the rendering library? https://github.com/neo4j-labs/arrows.app only contains a README. Thanks!

**Comment by Mogztter** [comment]
@johnymontana it's live!

live

**Comment by johnymontana** [comment]
Thanks, @Mogztter!

To answer your question about where the source for arrows lives - it's not currently open source. The linked Github repo is meant to collect and respond to issues only.

**Pull request merged**
